SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE >= '2022-01-01' AND C.SALES_DATE < '2022-02-01'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY 1 ASC, 3 DESC

# SELECT * FROM BOOK

# SELECT * FROM AUTHOR