SELECT e1.ID
FROM ECOLI_DATA AS e1
INNER JOIN (
    SELECT e2.ID
    FROM ECOLI_DATA AS e2
    INNER JOIN (
        SELECT e3.ID
        FROM ECOLI_DATA AS e3
        WHERE e3.PARENT_ID IS NULL
    ) AS A
        ON A.ID = e2.PARENT_ID
) AS C
    ON e1.PARENT_ID = C.ID
ORDER BY e1.ID;
