# SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, ROUND(30 * (A.DAILY_FEE - A.DAILY_FEE * (C.DISCOUNT_RATE / 100))) AS FEE FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON (A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = C.CAR_TYPE)
# WHERE (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단') AND B.END_DATE < '2022-11-01' AND C.DURATION_TYPE = '30일 이상' and ROUND(30 * (A.DAILY_FEE - A.DAILY_FEE * (C.DISCOUNT_RATE / 100))) >= 500000 and ROUND(30 * (A.DAILY_FEE - A.DAILY_FEE * (C.DISCOUNT_RATE / 100))) < 2000000
# ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;

WITH DISCOUNT_PLAN AS (SELECT *
                       FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                       WHERE DURATION_TYPE = '30일 이상'),
RENTED_NOV AS (SELECT DISTINCT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'),
FEE_CALC AS (SELECT C.CAR_ID,
                    C.CAR_TYPE,
                    FLOOR((C.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100.0)) * 30) AS FEE
             FROM CAR_RENTAL_COMPANY_CAR C JOIN DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
             WHERE C.CAR_TYPE IN ('세단', 'SUV'))

SELECT F.CAR_ID, F.CAR_TYPE, F.FEE
FROM FEE_CALC F
WHERE NOT EXISTS (SELECT 1
                  FROM RENTED_NOV R
                  WHERE R.CAR_ID = F.CAR_ID)
      AND F.FEE BETWEEN 500000 AND 1999999
ORDER BY F.FEE DESC, F.CAR_TYPE, F.CAR_ID DESC