WITH MORETHANTHREE AS (SELECT *
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3)

SELECT A.USER_ID, A.NICKNAME, CONCAT_WS(" ", A.CITY, A.STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소', CONCAT_WS("-", SUBSTRING(A.TLNO, 1, 3), SUBSTRING(A.TLNO, 4, 4), SUBSTRING(A.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS A
INNER JOIN MORETHANTHREE AS B
ON A.USER_ID = B.WRITER_ID
ORDER BY 1 DESC