-- 코드를 입력하세요
# SELECT 
#     YEAR(B.SALES_DATE) AS YEAR, 
#     MONTH(B.SALES_DATE) AS MONTH, 
#     COUNT(B.USER_ID) AS PURCHASED_USERS, 
#     ROUND(COUNT(B.USER_ID) / COUNT(A.USER_ID), 1) AS PURCHASED_RATIO
# FROM 
#     USER_INFO A
# INNER JOIN 
#     ONLINE_SALE B
# ON 
#     A.USER_ID = B.USER_ID
# WHERE 
#     YEAR(A.JOINED) = 2021
# GROUP BY 
#     YEAR, MONTH
# ORDER BY 
#     YEAR, MONTH;

# SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, COUNT(B.USER_ID) AS PURCHASED_USERS, (COUNT(B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%')) AS PURCHASED_RATIO
# FROM USER_INFO A
# INNER JOIN ONLINE_SALE B
# ON (A.USER_ID = B.USER_ID)
# WHERE A.JOINED LIKE '2021%'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH;

# SELECT 
#     YEAR(B.SALES_DATE) AS YEAR, 
#     MONTH(B.SALES_DATE) AS MONTH, 
#     COUNT(B.USER_ID) AS PURCHASED_USERS, 
#     ROUND((COUNT(B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%')),1) AS PURCHASED_RATIO
# FROM 
#     USER_INFO A
# INNER JOIN 
#     ONLINE_SALE B
# ON 
#     A.USER_ID = B.USER_ID
# WHERE 
#     A.JOINED LIKE '2021%'
# GROUP BY 
#     YEAR, MONTH
# ORDER BY 
#     YEAR, MONTH;

# WITH Total_Users_2021 AS (
#     SELECT COUNT(*) AS Total_Users
#     FROM USER_INFO
#     WHERE JOINED LIKE '2021%'
# )
# SELECT 
#     YEAR(B.SALES_DATE) AS YEAR, 
#     MONTH(B.SALES_DATE) AS MONTH, 
#     COUNT(B.USER_ID) AS PURCHASED_USERS, 
#     ROUND((COUNT(B.USER_ID) / T.Total_Users), 1) AS PURCHASED_RATIO
# FROM 
#     USER_INFO A
# INNER JOIN 
#     ONLINE_SALE B
# ON 
#     A.USER_ID = B.USER_ID
# INNER JOIN 
#     Total_Users_2021 T
# WHERE 
#     A.JOINED LIKE '2021%'
# GROUP BY 
#     YEAR, MONTH, T.Total_Users
# ORDER BY 
#     YEAR, MONTH;

# SELECT
#     YEAR (SALES_DATE) YEAR, 
#     MONTH (SALES_DATE) MONTH, 
#     COUNT (DISTINCT a.USER_ID) PURCHASED_USERS, 
#     Round(COUNT(DISTINCT a.USER_ID)/(SELECT COUNT (*) FROM USER_INFO WHERE JOINED LIKE '2021%'),     1) AS PUCHASED_RATIO
# FROM ONLINE_SALE a JOIN USER_INFO b
# ON a.USER_ID = b.USER_ID
# WHERE JOINED LIKE '2021%'
# GROUP BY 1, 2
# ORDER BY 1, 2
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PURCHASED_RATIO
FROM USER_INFO A
INNER JOIN ONLINE_SALE B
ON (A.USER_ID = B.USER_ID)
WHERE JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;