-- 코드를 입력하세요
SELECT A.NAME, A.DATETIME
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME) A
LEFT OUTER JOIN
ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
LIMIT 3;

# SELECT A.NAME, A.DATETIME
# FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME) A
# LEFT OUTER JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.ANIMAL_ID IS NULL
# ORDER BY A.DATETIME
# LIMIT 3;