WITH HISTORY AS (SELECT A.CAR_TYPE, B.HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION, A.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) AS FEE FROM CAR_RENTAL_COMPANY_CAR A RIGHT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON (A.CAR_ID = B.CAR_ID) WHERE A.CAR_TYPE = '트럭'),
DISCOUNT AS (SELECT CAR_TYPE, REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') * 1 AS DURATION, DISCOUNT_RATE * 1 AS DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN)

SELECT HISTORY_ID, CASE WHEN DURATION < 7 THEN FEE
                        WHEN DURATION >= 7 AND DURATION < 30 THEN FLOOR(FEE * (95 / 100))
                        WHEN DURATION >= 30 AND DURATION < 90 THEN FLOOR(FEE * (92 / 100))
                        ELSE FLOOR(FEE * (85 / 100)) END AS FEE FROM HISTORY
ORDER BY 2 DESC, 1 DESC

# SELECT * FROM HISTORY
























# SELECT H.HISTORY_ID, ROUND((DAILY_FEE * RENT_DAY) - (DAILY_FEE * RENT_DAY * 0.01 * IFNULL(MAX(DISCOUNT_RATE), 0))) AS FEE FROM CAR_RENTAL_COMPANY_CAR AS R
# JOIN (
#     SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# )  AS H ON R.CAR_ID = H.CAR_ID
# LEFT JOIN (
#     SELECT 
#         CAR_TYPE
#         , SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS DURATION_DATE
#         , CAST(SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS SIGNED) AS DISCOUNT_RATE
#     FROM  CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# ) AS D ON H.RENT_DAY > D.DURATION_DATE
# WHERE R.CAR_TYPE = '트럭' AND (D.CAR_TYPE = '트럭' OR D.CAR_TYPE IS NULL)
# GROUP BY HISTORY_ID
# ORDER BY FEE DESC, HISTORY_ID DESC