SELECT TT.FLAVOR FROM (SELECT T.FLAVOR, SUM(T.TOTAL_ORDER) AS TOTAL_ORDER FROM (SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM FIRST_HALF UNION ALL SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM JULY) AS T GROUP BY T.FLAVOR ORDER BY 2 DESC LIMIT 3) AS TT

# (SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM FIRST_HALF UNION ALL SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM JULY)

# SELECT * FROM FIRST_HALF

# SELECT * FROM JULY