SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P, DOCTOR D, APPOINTMENT A 
WHERE DATE(A.APNT_YMD) = '2022-04-13' 
AND A.APNT_CNCL_YN = "N" 
AND A.MCDP_CD = 'CS'
AND D.DR_ID = A.MDDR_ID
AND A.PT_NO = P.PT_NO
ORDER BY 6 ASC