WITH COND AS (
SELECT WRITER_ID, SUM(PRICE) AS SUM FROM USED_GOODS_BOARD WHERE STATUS = "DONE" GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000)

SELECT A.USER_ID, A.NICKNAME, B.SUM AS TOTAL_SALES
FROM USED_GOODS_USER AS A
INNER JOIN COND AS B
ON A.USER_ID = B.WRITER_ID
group by A.USER_ID
ORDER BY 3