WITH 
    CNT AS (SELECT A.MEMBER_ID, COUNT(A.MEMBER_ID) AS CNT, A.REVIEW_TEXT, A.REVIEW_DATE FROM REST_REVIEW A GROUP BY A.MEMBER_ID),
    MAX AS (SELECT MAX(CNT) AS MAX FROM CNT),
    MAXIST AS (SELECT R.MEMBER_ID, R.REVIEW_TEXT, R.REVIEW_DATE FROM REST_REVIEW R JOIN CNT C ON (R.MEMBER_ID = C.MEMBER_ID) WHERE C.CNT = (SELECT * FROM MAX))

SELECT P.MEMBER_NAME, M.REVIEW_TEXT, DATE_FORMAT(M.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE FROM MAXIST M JOIN MEMBER_PROFILE P
ON M.MEMBER_ID = P.MEMBER_ID
ORDER BY 3, 2
    


