# SELECT MONTH(END_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
# GROUP BY CAR_ID,
# HAVING COUNT(HISTORY_ID) >= 5
# ORDER BY 1 ASC, 2 DESC

# SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(H.HISTORY_ID) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
# INNER JOIN 
# (SELECT CAR_ID, COUNT(HISTORY_ID) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
# GROUP BY CAR_ID
# HAVING COUNT(HISTORY_ID) >= 5
# ORDER BY 1 ASC) AS T
# ON (H.CAR_ID = T.CAR_ID)
# GROUP BY MONTH(H.START_DATE), H.CAR_ID
# ORDER BY 1 ASC, 2 DESC

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE >= '2022-08-01' AND START_DATE <'2022-11-01'
                GROUP BY CAR_ID 
                 HAVING COUNT(*)>=5) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID HAVING COUNT(*) <> 0
ORDER BY MONTH ASC, CAR_ID DESC