SELECT CONCAT_WS('/', '/home', 'grep', 'src', A.BOARD_ID, CONCAT(B.FILE_ID, B.FILE_NAME, B.FILE_EXT)) AS FILE_PATH
FROM USED_GOODS_BOARD AS A
INNER JOIN 
USED_GOODS_FILE AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY 1 DESC

# SELECT * FROM USED_GOODS_BOARD

# SELECT * FROM USED_GOODS_FILE