SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES FROM BOOK AS B
RIGHT OUTER JOIN (SELECT * FROM BOOK_SALES WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01') AS BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
